services:
  pipeline:
    image: pipeline_image:latest
    container_name: pipeline_image
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'tester'
    ports:
      - 8000:8000
    depends_on:
      - postgres

  consumer:
    image: consumer_image:latest
    container_name: consumer_image
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'tester'
    depends_on:
      - postgres

  healthchecker:
    image: healthchecker_image:latest
    container_name: healthchecker_image
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'tester'
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: 'tester'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - /home/username/socket_dir:/var/run/postgresql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
