[tool.poetry]
name = "pipeliner"
packages = [
    { include = "pipeliner" },
]
version = "1.0.0"
description = ""
authors = ["Jwostik"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"